# Generated by Django 5.2 on 2025-04-13 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copies', models.PositiveBigIntegerField(default=0)),
                ('contact', models.PositiveIntegerField(default=0)),
                ('reservation_date', models.DateField()),
                ('status', models.BooleanField(default='Pending')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_book', to='Books.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
