# Generated by Django 5.2 on 2025-04-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_reservations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='status',
            field=models.CharField(default='Pending'),
        ),
    ]
